Casion PokeApi/Models/Pokemons/Pokemons.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;

namespace Casion_PokeApi.Models
{
    public class Pokemons
    {
        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        public Sprites Sprites { get; set; }

        public List<Types> Types { get; set; }

        public Pokemons() {}

        public Pokemons(int id, string name)
        {
            Id = id;
            Name = name;
        }        
    }
}

Casion PokeApi/Models/Pokemons/Sprites.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Casion_PokeApi.Models
{
    public class Sprites
    {

        [JsonProperty("front_default")]
        public string Front_default{ get; set; }

    }
}

Casion PokeApi/Models/Pokemons/Type.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Casion_PokeApi.Models
{
    public class Type
    {

        [JsonProperty("name")]
        public string Name { get; set; }

    }
}

Casion PokeApi/Models/Pokemons/Types.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Casion_PokeApi.Models
{
    public class Types
    {
                
        [JsonProperty("type")]
        public Type Type { get; set; }               
        
    }
}

Casion PokeApi/Controllers/PokemonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Casion_PokeApi.Models;
using Newtonsoft.Json;

namespace Casion_PokeApi.Controllers
{
    public class PokemonsController : Controller
    {
        public async Task<ActionResult> Index()
        {
            ViewBag.Title = "Casion Pokedex";
            ViewBag.Message = "";

            List<Pokemons> listaPokemons = new List<Pokemons>();

            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("aplication/json"));
                string url = $"https://davilson.github.io/casion-tech-goodies-tests/casion-test-full-stack-dot-net/poke_api.json";

                var response = client.GetAsync(url).Result;

                if (response.IsSuccessStatusCode)
                {
                    response.EnsureSuccessStatusCode();
                    string content = await response.Content.ReadAsStringAsync();
                    listaPokemons = JsonConvert.DeserializeObject<List<Pokemons>>(content);
                    ViewBag.Contador = listaPokemons.Count();
                }
                else
                {
                    var result = response.Content.ReadAsStringAsync().Result;
                    throw new Exception(result);
                }
            }           
            
            return View(listaPokemons);

        }                     
    }
}

Casion PokeApi/Views/Pokemons/Index.cshtml
@model List<Casion_PokeApi.Models.Pokemons>

<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<p class="text-right">@ViewBag.Contador</p>
<hr />

<div class="row">

    @foreach (var item in Model)
    {
        <div class="tab-content line-poke ">
            <div class="col-sm-3">
                <div class="card card-poke">
                    <div class="card-body">
                        <div class="fade-img">
                            <p class="card-text text-Id">@item.Id</p>
                            <p class="card-text text-Name">@item.Name</p>

                            <div class="img-poke">
                                <img src="@item.Sprites.Front_default" alt="@item.Name">
                            </div>
                        </div>
                        <div class="type">
                            <p class="card-text badge">@item.Types[0].Type.Name</p>
                            @if (item.Types.Count == 2)
                            {
                                <p class="card-text badge badge-poke">@item.Types[1].Type.Name</p>
                            }                            
                        </div>
                        @*<div class="fade">
                            <span class="fade-retangulo"> </span>
                            <span class="fade-ret"> </span>
                        </div>*@
                        </div>
                </div>
            </div>
        </div>            
    }
</div>

Casion PokeApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/Poke.css")
    @Scripts.Render("~/bundles/modernizr")    
</head>

<body style="background: #000002; color: #ffffff;">
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color: #DC0A2D;">
        <div class="container">
            <div class="nav-poke">
                <div class="frame-elipse"> </div>
                <p>Casion Pokedex</p>
                <div class="frame">
                    <div class="group"></div>
                    <p>Ash</p>
                </div>
            </div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Casion Pokedex", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                @*<ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Início", "Index", "Pokemons")</li>
                  </ul>*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <dl class="row">
                <dd class="col-sm-3">&copy; @DateTime.Now.Year - Casion</dd>
                <dd class="text-right col-sm-9">#TechGoodies</dd>
            </dl>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>